//! Builds the [`MountTable`] from enumerated disks and the real device ids.
//!
//! The volumes come from a [`DiskEnumerator`](crate::ports::DiskEnumerator); this
//! module only adds what `diskutil` does not report: the `st_dev` of every mount
//! point and, for the Data volume, the firmlinks that make `/Users` live on it
//! (`docs/adr/0002-diskutil-plist-over-diskarbitration.md`). It never runs
//! `diskutil` itself.

use std::path::{Path, PathBuf};

use crate::BrozaError;
use crate::adapters::std_fs::StdFileOps;
use crate::model::{Disk, Volume, VolumeRole};
use crate::ports::FileOps;
use crate::scan::{MountEntry, MountTable};

/// Where macOS records the firmlinks of the current system.
pub const FIRMLINKS_PATH: &str = "/usr/share/firmlinks";
/// Character separating the system path from the data-relative path.
const FIRMLINK_SEPARATOR: char = '\t';
/// Character starting a comment line.
const COMMENT_PREFIX: char = '#';

/// Mount table of the running system for `disks`.
pub fn system_mount_table(disks: &[Disk]) -> Result<MountTable, BrozaError> {
    mount_table_from(&StdFileOps, disks, Path::new(FIRMLINKS_PATH))
}

/// Mount table of `disks`, reading device ids and firmlinks through `fs`.
///
/// A volume with no mount point, or whose mount point has disappeared since the
/// enumeration, contributes no entry: an unmounted volume owns no path. Any other
/// failure to stat a mount point is returned to the caller.
pub fn mount_table_from(
    fs: &dyn FileOps,
    disks: &[Disk],
    firmlinks_path: &Path,
) -> Result<MountTable, BrozaError> {
    let firmlinks = read_firmlinks(fs, firmlinks_path)?;
    let mut entries = Vec::new();
    for volume in disks.iter().flat_map(|disk| &disk.containers).flat_map(|container| &container.volumes) {
        if let Some(entry) = entry_for(fs, volume, &firmlinks)? {
            entries.push(entry);
        }
    }
    Ok(MountTable::new(entries))
}

/// Parse the firmlinks file, keeping the absolute system paths.
///
/// Format: one `<system path>\t<data-relative path>` per line. Comments, blank
/// lines, and anything that is not an absolute system path are ignored, because an
/// unparsable line must never turn into a wrong volume attribution.
pub fn parse_firmlinks(contents: &str) -> Vec<PathBuf> {
    contents
        .lines()
        .map(str::trim_end)
        .filter(|line| !line.is_empty() && !line.starts_with(COMMENT_PREFIX))
        .filter_map(|line| line.split_once(FIRMLINK_SEPARATOR))
        .map(|(system_path, _)| system_path.trim())
        .filter(|system_path| Path::new(system_path).is_absolute())
        .map(PathBuf::from)
        .collect()
}

/// Read and parse the firmlinks file; an absent file means no firmlinks.
fn read_firmlinks(fs: &dyn FileOps, path: &Path) -> Result<Vec<PathBuf>, BrozaError> {
    if !fs.exists(path) {
        return Ok(Vec::new());
    }
    let raw = fs.read(path)?;
    Ok(parse_firmlinks(&String::from_utf8_lossy(&raw)))
}

/// Build the entry of one volume, or `None` when it owns no live mount point.
fn entry_for(
    fs: &dyn FileOps,
    volume: &Volume,
    firmlinks: &[PathBuf],
) -> Result<Option<MountEntry>, BrozaError> {
    let Some(mount_point) = volume.mount_point.clone() else { return Ok(None) };
    let device = match fs.metadata(&mount_point) {
        Ok(metadata) => metadata.device,
        Err(BrozaError::TargetNotFound(_)) => return Ok(None),
        Err(error) => return Err(error),
    };
    let firmlinks = if volume.role == VolumeRole::Data { firmlinks.to_vec() } else { Vec::new() };
    Ok(Some(MountEntry { mount_point, device, volume: volume.clone(), firmlinks }))
}

#[cfg(test)]
mod tests {
    use std::path::{Path, PathBuf};

    use super::{FIRMLINKS_PATH, mount_table_from, parse_firmlinks, system_mount_table};
    use crate::model::{Container, Disk, FsKind, Volume, VolumeRole};
    use crate::testing::FakeFileOps;

    /// A firmlinks file as macOS writes it, plus the lines a parser must survive.
    const FIRMLINKS_SAMPLE: &str = "\
# generated by the installer

/Applications\tApplications
/Users\tUsers
/private\tprivate
relative/path\trelative
/no-tab-here
";

    fn volume(id: &str, role: VolumeRole, mount: Option<&str>) -> Volume {
        Volume {
            id: id.parse().unwrap_or_else(|e| panic!("{e}")),
            name: id.to_owned(),
            role,
            mount_point: mount.map(PathBuf::from),
            used_bytes: 0,
            writable_by_broza: role.writable_by_broza(),
            purpose: String::new(),
        }
    }

    fn disks(volumes: Vec<Volume>) -> Vec<Disk> {
        vec![Disk {
            id: "disk0".parse().unwrap_or_else(|e| panic!("{e}")),
            model: "Apple SSD".to_owned(),
            size_bytes: 0,
            internal: true,
            containers: vec![Container {
                id: "disk3".parse().unwrap_or_else(|e| panic!("{e}")),
                kind: FsKind::Apfs,
                size_bytes: 0,
                used_bytes: 0,
                free_bytes: 0,
                purgeable_bytes: 0,
                volumes,
            }],
        }]
    }

    fn mac_like_fs() -> FakeFileOps {
        FakeFileOps::new()
            .with_root("/", 1)
            .with_root("/System/Volumes/Data", 2)
            .with_file(FIRMLINKS_PATH, FIRMLINKS_SAMPLE.as_bytes())
    }

    #[test]
    fn parsing_keeps_the_absolute_system_paths_only() {
        let parsed = parse_firmlinks(FIRMLINKS_SAMPLE);

        assert_eq!(
            parsed,
            vec![PathBuf::from("/Applications"), PathBuf::from("/Users"), PathBuf::from("/private")]
        );
    }

    #[test]
    fn parsing_an_empty_file_yields_no_firmlinks() {
        assert!(parse_firmlinks("").is_empty());
        assert!(parse_firmlinks("\n\n# only comments\n").is_empty());
    }

    #[test]
    fn every_mounted_volume_gets_the_device_of_its_mount_point() {
        let fs = mac_like_fs();
        let volumes = vec![
            volume("disk3s1", VolumeRole::System, Some("/")),
            volume("disk3s5", VolumeRole::Data, Some("/System/Volumes/Data")),
        ];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        assert_eq!(table.entries().len(), 2);
        assert_eq!(table.by_device(1).map(|entry| entry.volume.role), Some(VolumeRole::System));
        assert_eq!(table.by_device(2).map(|entry| entry.volume.role), Some(VolumeRole::Data));
    }

    #[test]
    fn only_the_data_volume_carries_the_firmlinks() {
        let fs = mac_like_fs();
        let volumes = vec![
            volume("disk3s1", VolumeRole::System, Some("/")),
            volume("disk3s5", VolumeRole::Data, Some("/System/Volumes/Data")),
        ];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        let data = table.by_device(2).unwrap_or_else(|| panic!("no data volume"));
        assert!(data.firmlinks.contains(&PathBuf::from("/Users")));
        assert_eq!(table.by_device(1).map(|entry| entry.firmlinks.len()), Some(0));
    }

    #[test]
    fn a_firmlinked_path_resolves_to_the_data_volume() {
        let fs = mac_like_fs();
        let volumes = vec![
            volume("disk3s1", VolumeRole::System, Some("/")),
            volume("disk3s5", VolumeRole::Data, Some("/System/Volumes/Data")),
        ];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        assert_eq!(table.role_for(Path::new("/Users/dana/Downloads")), Some(VolumeRole::Data));
        assert_eq!(table.role_for(Path::new("/System/Library")), Some(VolumeRole::System));
    }

    #[test]
    fn a_volume_without_a_mount_point_produces_no_entry() {
        let fs = mac_like_fs();
        let volumes = vec![volume("disk3s2", VolumeRole::Preboot, None)];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        assert!(table.entries().is_empty());
    }

    #[test]
    fn a_mount_point_that_disappeared_is_skipped() {
        let fs = mac_like_fs();
        let volumes = vec![volume("disk4s1", VolumeRole::User, Some("/Volumes/Gone"))];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        assert!(table.entries().is_empty());
    }

    #[test]
    fn a_missing_firmlinks_file_leaves_the_data_volume_without_firmlinks() {
        let fs = FakeFileOps::new().with_root("/System/Volumes/Data", 2);
        let volumes = vec![volume("disk3s5", VolumeRole::Data, Some("/System/Volumes/Data"))];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        assert_eq!(table.by_device(2).map(|entry| entry.firmlinks.len()), Some(0));
    }

    #[test]
    fn the_system_table_of_no_disks_is_empty() {
        // Enumerates nothing and reads no disk: the only real file it may touch is
        // the firmlinks list, which every supported macOS ships read-only.
        let table = system_mount_table(&[]).unwrap_or_else(|e| panic!("{e}"));

        assert!(table.entries().is_empty());
    }

    #[test]
    fn entries_keep_the_order_the_enumerator_reported() {
        let fs = mac_like_fs();
        let volumes = vec![
            volume("disk3s5", VolumeRole::Data, Some("/System/Volumes/Data")),
            volume("disk3s1", VolumeRole::System, Some("/")),
        ];

        let table = mount_table_from(&fs, &disks(volumes), Path::new(FIRMLINKS_PATH))
            .unwrap_or_else(|e| panic!("{e}"));

        let devices: Vec<u64> = table.entries().iter().map(|entry| entry.device).collect();
        assert_eq!(devices, vec![2, 1]);
    }
}
