//! `user-cache`: what applications rebuild on their own (`docs/cli-spec.md` §3.3).
//!
//! Three findings, all green and all quarantine:
//!
//! - `user-cache.library-caches` — every top-level entry of `~/Library/Caches`;
//! - `user-cache.logs` — every top-level entry of `~/Library/Logs`;
//! - `user-cache.incomplete-downloads` — partial downloads left in `~/Downloads`
//!   by browsers (`.download`, `.crdownload`, `.part`).
//!
//! Each finding lists its paths one level below the root, so a user reading the
//! plan sees `com.apple.Safari` and `Homebrew`, not one opaque `Caches` line.
//! A cache entry that holds something no application rebuilds — `JetBrains` keeps
//! per-file undo history under `Caches/JetBrains/<IDE>/LocalHistory` — is opened
//! up instead: its children are listed without the data-bearing one, so the
//! green label stays true of every path under it.
//!
//! `~/Downloads` is often off limits without Full Disk Access. That costs the
//! third finding and a warning, never the other two.

use std::path::Path;

use crate::BrozaError;
use crate::model::{Category, Finding, FindingPath};
use crate::scan::DirNode;

use super::support::{by_size_then_path, finish, path_of, path_with, start};
use crate::detect::detector::{DetectContext, Detected, Detector};

/// Suffixes browsers give a download that has not finished.
const INCOMPLETE_SUFFIXES: [&str; 3] = [".download", ".crdownload", ".part"];
/// Directory names under `~/Library/Caches` that hold data nothing regenerates:
/// `JetBrains`' per-file undo history (two spellings across IDE versions), and
/// Poetry's virtual environments (a
/// `pip install` of every project's dependencies, not a cache of them).
const DATA_BEARING_DIRS: [&str; 3] = ["LocalHistory", "fileHistory", "virtualenvs"];
/// How many levels a cache entry is opened up to isolate a data-bearing directory.
const MAX_OPEN_DEPTH: usize = 3;

/// The `user-cache` detector.
pub struct UserCache;

impl Detector for UserCache {
    fn category(&self) -> Category {
        Category::UserCache
    }

    fn detect(&self, context: &DetectContext<'_>) -> Result<Detected, BrozaError> {
        let caches = children_finding(
            context,
            "Library/Caches",
            "library-caches",
            "Application caches",
            "Caches applications rebuild on demand; removing them costs a slower first launch.",
        )?;
        let logs = children_finding(
            context,
            "Library/Logs",
            "logs",
            "Application logs",
            "Diagnostic logs kept by applications; nothing reads them back except a support engineer.",
        )?;
        Ok(Detected::default().with_finding(caches).with_finding(logs).merged(incomplete_downloads(context)?))
    }
}

/// One finding over the direct children of `~/<relative>`, as the walk measured them.
fn children_finding(
    context: &DetectContext<'_>,
    relative: &str,
    detector: &str,
    title: &str,
    description: &str,
) -> Result<Option<Finding>, BrozaError> {
    let root = context.under_home(relative);
    let data_bearing: Vec<&DirNode> =
        DATA_BEARING_DIRS.iter().flat_map(|name| context.nodes_named(name)).collect();
    let mut paths: Vec<FindingPath> = context
        .children_of(&root)
        .flat_map(|node| regenerable_paths(context, node, &data_bearing, 0))
        .filter(|path| path.size_bytes > 0)
        .collect();
    paths.sort_by(by_size_then_path);
    let builder = start(Category::UserCache, detector, title)?.description(description).reasoning(format!(
        "Everything under {} is regenerated by the application that owns it.",
        root.display()
    ));
    finish(builder, paths)
}

/// `node` as one path, or its children without the data-bearing ones when a
/// directory nothing regenerates sits inside it.
fn regenerable_paths(
    context: &DetectContext<'_>,
    node: &DirNode,
    data_bearing: &[&DirNode],
    depth: usize,
) -> Vec<FindingPath> {
    if is_data_bearing(&node.path) {
        return Vec::new();
    }
    if !data_bearing.iter().any(|kept| kept.path.starts_with(&node.path)) {
        return vec![path_of(node)];
    }
    if depth >= MAX_OPEN_DEPTH {
        return Vec::new();
    }
    context
        .children_of(&node.path)
        .flat_map(|child| regenerable_paths(context, child, data_bearing, depth + 1))
        .collect()
}

/// `true` when `path` is one of the directories nothing regenerates.
fn is_data_bearing(path: &Path) -> bool {
    path.file_name().is_some_and(|name| DATA_BEARING_DIRS.iter().any(|kept| name == *kept))
}

/// Partial downloads in `~/Downloads`, found by name; a warning when unreadable.
fn incomplete_downloads(context: &DetectContext<'_>) -> Result<Detected, BrozaError> {
    let downloads = context.under_home("Downloads");
    if !context.fs.exists(&downloads) {
        return Ok(Detected::default());
    }
    let listing = match context.fs.read_dir_with_metadata(&downloads) {
        Ok(listing) => listing,
        Err(error) => {
            let warning =
                Detected::unreadable(Category::UserCache, &downloads, "incomplete downloads", &error);
            return Ok(Detected { findings: Vec::new(), warnings: vec![warning] });
        }
    };
    let mut paths: Vec<_> = listing
        .into_iter()
        .filter(|(path, _)| is_incomplete(path))
        .filter_map(|(path, meta)| {
            meta.ok().map(|meta| path_with(&path, meta.allocated_bytes, meta.modified))
        })
        .collect();
    paths.sort_by(by_size_then_path);
    let builder = start(Category::UserCache, "incomplete-downloads", "Incomplete downloads")?
        .description("Downloads a browser started and never finished.")
        .reasoning("A partial download cannot be resumed once the browser has forgotten it.");
    Ok(Detected::default().with_finding(finish(builder, paths)?))
}

/// `true` when `path` carries one of the suffixes browsers use while downloading.
fn is_incomplete(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| INCOMPLETE_SUFFIXES.iter().any(|suffix| name.ends_with(suffix)))
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::detect::detector::LOCATION_UNREADABLE_CODE;
    use crate::detect::test_support::{context_over, home};
    use crate::testing::FakeFileOps;

    fn fs() -> FakeFileOps {
        let fs = FakeFileOps::new().with_root("/System/Volumes/Data", 2);
        for (path, size) in [
            ("/System/Volumes/Data/Users/dana/Library/Caches/com.apple.Safari/a.db", 5000_u64),
            ("/System/Volumes/Data/Users/dana/Library/Caches/Homebrew/b.tgz", 9000),
            ("/System/Volumes/Data/Users/dana/Library/Logs/App/app.log", 100),
            ("/System/Volumes/Data/Users/dana/Downloads/movie.mp4.part", 4000),
            ("/System/Volumes/Data/Users/dana/Downloads/done.pdf", 4000),
        ] {
            fs.add_file(path, &[]);
            fs.set_size(path, size);
        }
        fs
    }

    fn detect(fs: &FakeFileOps) -> Detected {
        let world = context_over(fs, home());
        UserCache.detect(&world.context()).unwrap_or_else(|e| panic!("{e}"))
    }

    fn by_id<'a>(detected: &'a Detected, id: &str) -> &'a Finding {
        detected.findings.iter().find(|f| f.id().to_string() == id).unwrap_or_else(|| panic!("{id}"))
    }

    fn names(finding: &Finding) -> Vec<String> {
        finding.paths().iter().map(|p| p.path.file_name().unwrap().to_string_lossy().into_owned()).collect()
    }

    #[test]
    fn caches_are_listed_one_level_down_biggest_first() {
        let detected = detect(&fs());

        let caches = by_id(&detected, "user-cache.library-caches");
        assert_eq!(names(caches), vec!["Homebrew", "com.apple.Safari"]);
        assert_eq!(caches.reclaimable_bytes(), 3 * 4096 + 2 * 4096, "allocated blocks of both");
        assert_eq!(caches.item_count(), Some(2));
        assert!(detected.warnings.is_empty());
    }

    #[test]
    fn a_cache_holding_jetbrains_local_history_is_opened_up_around_it() {
        let fs = fs();
        let jb = "/System/Volumes/Data/Users/dana/Library/Caches/JetBrains";
        for (path, size) in [
            (format!("{jb}/IntelliJIdea2025.1/LocalHistory/changes.storageData"), 50_000_u64),
            (format!("{jb}/IntelliJIdea2025.1/caches/names.dat"), 20_000),
            (format!("{jb}/IntelliJIdea2025.1/index/stubs.dat"), 10_000),
            (format!("{jb}/CLion2025.1/caches/x.dat"), 1000),
        ] {
            fs.add_file(&path, &[]);
            fs.set_size(&path, size);
        }

        let detected = detect(&fs);

        let caches = by_id(&detected, "user-cache.library-caches");
        let listed: Vec<String> = caches.paths().iter().map(|p| p.path.display().to_string()).collect();
        assert!(listed.contains(&format!("{jb}/IntelliJIdea2025.1/caches")), "{listed:?}");
        assert!(listed.contains(&format!("{jb}/IntelliJIdea2025.1/index")), "{listed:?}");
        assert!(
            listed.contains(&format!("{jb}/CLion2025.1")),
            "an IDE without history stays whole: {listed:?}"
        );
        assert!(
            listed.iter().all(|p| !p.contains("LocalHistory") && !p.ends_with("/JetBrains")),
            "{listed:?}"
        );
    }

    #[test]
    fn poetry_virtualenvs_under_caches_are_kept_and_their_siblings_listed() {
        let fs = fs();
        let poetry = "/System/Volumes/Data/Users/dana/Library/Caches/pypoetry";
        for (path, size) in [
            (format!("{poetry}/virtualenvs/app-py3.12/lib/site.py"), 50_000_u64),
            (format!("{poetry}/artifacts/ab/wheel.whl"), 20_000),
            (format!("{poetry}/cache/repositories/pypi/x.json"), 1000),
        ] {
            fs.add_file(&path, &[]);
            fs.set_size(&path, size);
        }

        let detected = detect(&fs);

        let listed: Vec<String> = by_id(&detected, "user-cache.library-caches")
            .paths()
            .iter()
            .map(|p| p.path.display().to_string())
            .collect();
        assert!(listed.contains(&format!("{poetry}/artifacts")), "{listed:?}");
        assert!(listed.contains(&format!("{poetry}/cache")), "{listed:?}");
        assert!(listed.iter().all(|p| !p.contains("virtualenvs") && p != poetry), "{listed:?}");
    }

    #[test]
    fn only_partial_downloads_are_reported_and_finished_ones_are_left_alone() {
        let detected = detect(&fs());

        let partial = by_id(&detected, "user-cache.incomplete-downloads");
        assert_eq!(partial.paths().len(), 1);
        assert!(partial.paths()[0].path.ends_with("movie.mp4.part"));
    }

    #[test]
    fn an_unreadable_downloads_folder_costs_one_finding_and_one_warning_not_the_category() {
        let fs = fs().with_denied("/System/Volumes/Data/Users/dana/Downloads");

        let detected = detect(&fs);

        let ids: Vec<String> = detected.findings.iter().map(|f| f.id().to_string()).collect();
        assert_eq!(ids, vec!["user-cache.library-caches", "user-cache.logs"]);
        assert_eq!(detected.warnings.len(), 1, "{:?}", detected.warnings);
        assert_eq!(detected.warnings[0].code, LOCATION_UNREADABLE_CODE);
        assert!(detected.warnings[0].message.contains("incomplete downloads were not checked"));
    }

    #[test]
    fn a_home_with_nothing_to_report_yields_no_findings() {
        let fs = FakeFileOps::new().with_root("/System/Volumes/Data", 2);
        fs.add_dir("/System/Volumes/Data/Users/dana");

        let detected = detect(&fs);

        assert!(detected.findings.is_empty(), "{:?}", detected.findings);
        assert!(detected.warnings.is_empty());
    }
}
