//! `user-cache`: what applications rebuild on their own (`docs/cli-spec.md` §3.3).
//!
//! Three findings, all green and all quarantine:
//!
//! - `user-cache.library-caches` — every top-level entry of `~/Library/Caches`;
//! - `user-cache.logs` — every top-level entry of `~/Library/Logs`;
//! - `user-cache.incomplete-downloads` — partial downloads left in `~/Downloads`
//!   by browsers (`.download`, `.crdownload`, `.part`).
//!
//! Each finding lists its paths one level below the root, so a user reading the
//! plan sees `com.apple.Safari` and `Homebrew`, not one opaque `Caches` line.
//! Broza's own cache is left out: a tool listing itself as clutter is a tool
//! that changes its answer every run.

use std::path::Path;

use crate::BrozaError;
use crate::model::{Category, Finding};

use super::support::{finish, path_of, path_with, start};
use crate::detect::detector::{DetectContext, Detector};

/// Suffixes browsers give a download that has not finished.
const INCOMPLETE_SUFFIXES: [&str; 3] = [".download", ".crdownload", ".part"];
/// Broza's own scan cache, never a finding.
const OWN_CACHE_DIR: &str = "broza";

/// The `user-cache` detector.
pub struct UserCache;

impl Detector for UserCache {
    fn category(&self) -> Category {
        Category::UserCache
    }

    fn detect(&self, context: &DetectContext<'_>) -> Result<Vec<Finding>, BrozaError> {
        let mut findings = Vec::new();
        findings.extend(children_finding(
            context,
            "Library/Caches",
            "library-caches",
            "Application caches",
            "Caches applications rebuild on demand; removing them costs a slower first launch.",
        )?);
        findings.extend(children_finding(
            context,
            "Library/Logs",
            "logs",
            "Application logs",
            "Diagnostic logs kept by applications; nothing reads them back except a support engineer.",
        )?);
        findings.extend(incomplete_downloads(context)?);
        Ok(findings)
    }
}

/// One finding over the direct children of `~/<relative>`, as the walk measured them.
fn children_finding(
    context: &DetectContext<'_>,
    relative: &str,
    detector: &str,
    title: &str,
    description: &str,
) -> Result<Option<Finding>, BrozaError> {
    let root = context.under_home(relative);
    let mut paths: Vec<_> = context
        .children_of(&root)
        .filter(|node| node.path.file_name().is_none_or(|name| name != OWN_CACHE_DIR))
        .filter(|node| node.allocated_bytes > 0)
        .map(path_of)
        .collect();
    paths.sort_by(|a, b| b.size_bytes.cmp(&a.size_bytes).then_with(|| a.path.cmp(&b.path)));
    let builder = start(Category::UserCache, detector, title)?.description(description).reasoning(format!(
        "Everything under {} is regenerated by the application that owns it.",
        root.display()
    ));
    finish(builder, paths)
}

/// Partial downloads in `~/Downloads`, found by name.
fn incomplete_downloads(context: &DetectContext<'_>) -> Result<Option<Finding>, BrozaError> {
    let downloads = context.under_home("Downloads");
    if !context.fs.exists(&downloads) {
        return Ok(None);
    }
    let listing = context.fs.read_dir_with_metadata(&downloads)?;
    let mut paths: Vec<_> = listing
        .into_iter()
        .filter(|(path, _)| is_incomplete(path))
        .filter_map(|(path, meta)| {
            meta.ok().map(|meta| path_with(&path, meta.allocated_bytes, meta.modified))
        })
        .collect();
    paths.sort_by(|a, b| a.path.cmp(&b.path));
    let builder = start(Category::UserCache, "incomplete-downloads", "Incomplete downloads")?
        .description("Downloads a browser started and never finished.")
        .reasoning("A partial download cannot be resumed once the browser has forgotten it.");
    finish(builder, paths)
}

/// `true` when `path` carries one of the suffixes browsers use while downloading.
fn is_incomplete(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| INCOMPLETE_SUFFIXES.iter().any(|suffix| name.ends_with(suffix)))
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::detect::test_support::{context_over, home};
    use crate::testing::FakeFileOps;

    fn fs() -> FakeFileOps {
        let fs = FakeFileOps::new().with_root("/System/Volumes/Data", 2);
        for (path, size) in [
            ("/System/Volumes/Data/Users/dana/Library/Caches/com.apple.Safari/a.db", 5000_u64),
            ("/System/Volumes/Data/Users/dana/Library/Caches/Homebrew/b.tgz", 9000),
            ("/System/Volumes/Data/Users/dana/Library/Caches/broza/v1/x.bin", 700),
            ("/System/Volumes/Data/Users/dana/Library/Logs/app.log", 100),
            ("/System/Volumes/Data/Users/dana/Downloads/movie.mp4.part", 4000),
            ("/System/Volumes/Data/Users/dana/Downloads/done.pdf", 4000),
        ] {
            fs.add_file(path, &[]);
            fs.set_size(path, size);
        }
        fs
    }

    #[test]
    fn caches_are_listed_one_level_down_biggest_first_without_brozas_own() {
        let fs = fs();
        let world = context_over(&fs, home());

        let findings = UserCache.detect(&world.context()).unwrap_or_else(|e| panic!("{e}"));

        let caches = findings.iter().find(|f| f.id().to_string() == "user-cache.library-caches").unwrap();
        let names: Vec<_> = caches
            .paths()
            .iter()
            .map(|p| p.path.file_name().unwrap().to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, vec!["Homebrew", "com.apple.Safari"]);
        assert_eq!(caches.reclaimable_bytes(), 3 * 4096 + 2 * 4096, "allocated blocks of both, not of broza");
        assert_eq!(caches.item_count(), Some(2));
    }

    #[test]
    fn only_partial_downloads_are_reported_and_finished_ones_are_left_alone() {
        let fs = fs();
        let world = context_over(&fs, home());

        let findings = UserCache.detect(&world.context()).unwrap_or_else(|e| panic!("{e}"));

        let partial =
            findings.iter().find(|f| f.id().to_string() == "user-cache.incomplete-downloads").unwrap();
        assert_eq!(partial.paths().len(), 1);
        assert!(partial.paths()[0].path.ends_with("movie.mp4.part"));
    }

    #[test]
    fn a_home_with_nothing_to_report_yields_no_findings() {
        let fs = FakeFileOps::new().with_root("/System/Volumes/Data", 2);
        fs.add_dir("/System/Volumes/Data/Users/dana");
        let world = context_over(&fs, home());

        let findings = UserCache.detect(&world.context()).unwrap_or_else(|e| panic!("{e}"));

        assert!(findings.is_empty(), "{findings:?}");
    }
}
